#!/usr/bin/env python3
"""
xpoz-cli — standalone CLI wrapper around the xpoz Python SDK.

Only external dependency: the `xpoz` package itself (pip install xpoz).
All other functionality uses the Python stdlib.

Platform namespaces and their methods are discovered dynamically from the
installed SDK, so every method the SDK exposes becomes a CLI subcommand
automatically.

Usage:
    xpoz_cli.py [global-opts] <platform> <method> [--arg value ...]

Platforms:
    twitter | instagram | reddit | tiktok

Discovery:
    xpoz_cli.py --help
    xpoz_cli.py twitter --help
    xpoz_cli.py twitter search_posts --help

Examples:
    xpoz_cli.py twitter get_user --identifier elonmusk
    xpoz_cli.py twitter search_posts --query '"AI" AND ethics' \
        --start-date 2025-01-01 --limit 20 --fields id text like_count
    xpoz_cli.py reddit search_posts --query "python tutorial" \
        --subreddit learnpython --sort top --time month --all-pages
    xpoz_cli.py twitter search_posts --query bitcoin \
        --response-type csv --export-csv-url

Auth:
    --api-key KEY   (or env: XPOZ_API_KEY)
    --server-url U  (or env: XPOZ_SERVER_URL)
"""

from __future__ import annotations

import argparse
import inspect
import json
import os
import re
import sys
import types
import typing
import webbrowser
from enum import Enum

# BaseExceptionGroup is a builtin in 3.11+; for 3.10 use the PyPI backport.
# anyio (used by the SDK) raises real ExceptionGroup instances either way.
if sys.version_info < (3, 11):
    from exceptiongroup import BaseExceptionGroup  # noqa: F401

try:
    from xpoz import XpozClient, ResponseType  # type: ignore
    from xpoz.namespaces import (  # type: ignore
        TwitterNamespace,
        InstagramNamespace,
        RedditNamespace,
        TiktokNamespace,
        TrackingNamespace,
    )
except ImportError as _e:
    sys.stderr.write(f"xpoz SDK import failed: {_e}\nRun: pip install xpoz\n")
    sys.exit(2)

try:
    from _xpoz_cli_version import __version__  # generated by setuptools-scm
except ImportError:
    __version__ = "0+unknown"


# ---------- resilience against SDK type-declaration bugs ----------
#
# The SDK validates API responses through `model.model_validate(...)`. When a
# pydantic field type declaration disagrees with what the API actually returns
# (e.g. a field declared `str` that the API returns as `int`), validation
# raises `ValidationError` and the user sees a crash with no data.
#
# Patch `model_validate` on every result model used by the SDK so that a
# failure falls back to `model.model_construct(...)`. `model_construct` skips
# type checking and coercion entirely — the user gets the raw data with
# whatever types the API returned, which the CLI then JSON-dumps as-is. A
# single warning per (model, error) pair is emitted to stderr so the
# regression is visible without drowning paginated output.
#
# This is a defensive monkey-patch on the SDK's pydantic models. If a future
# SDK release stops using `model_validate` (unlikely — it's the canonical
# pydantic v2 entry point), the shim silently no-ops and the CLI reverts to
# the SDK's strict behavior, same as today.
try:
    from pydantic import BaseModel as _PydBaseModel

    _xpoz_seen_warnings: set = set()

    def _patch_model_validate(cls):
        """Wrap cls.model_validate to fall back to model_construct on error.

        cls.model_validate is a pydantic classmethod, accessed as a bound
        method (cls is auto-injected). We replace it with a plain function
        attribute; subsequent `cls.model_validate(data)` calls go straight
        to our function with `data` as the first positional arg.
        """
        orig = cls.model_validate  # bound method — cls already captured
        if getattr(orig, "_xpoz_resilient", False):
            return  # already patched

        def resilient(data, **kw):
            try:
                return orig(data, **kw)
            except Exception as exc:
                # Dedup on (model, field-path, error-kind) so we get one
                # warning per distinct issue across paginated rows.
                if hasattr(exc, "errors") and callable(exc.errors):
                    try:
                        errs = exc.errors()
                    except Exception:
                        errs = []
                    if errs:
                        first = errs[0]
                        loc = ".".join(str(p) for p in (first.get("loc") or ()))
                        key = (cls.__name__, loc, first.get("type", ""))
                        detail = f"{loc}: {first.get('type', '')}"
                    else:
                        key = (cls.__name__, type(exc).__name__)
                        detail = type(exc).__name__
                else:
                    key = (cls.__name__, type(exc).__name__, str(exc)[:200])
                    detail = type(exc).__name__
                if key not in _xpoz_seen_warnings:
                    _xpoz_seen_warnings.add(key)
                    sys.stderr.write(
                        f"warning: SDK validation failed for {cls.__name__} "
                        f"[{detail}] — falling back to raw data; types may "
                        f"not match the SDK's annotations.\n"
                    )
                if isinstance(data, dict):
                    try:
                        return cls.model_construct(**data)
                    except Exception:
                        pass
                raise exc

        resilient._xpoz_resilient = True  # type: ignore[attr-defined]
        cls.model_validate = resilient  # type: ignore[assignment]

    # Apply to every BaseModel subclass currently visible under xpoz.types.
    import xpoz.types as _xpoz_types  # noqa: F401
    import pkgutil, importlib
    for _mod_info in pkgutil.iter_modules(_xpoz_types.__path__):
        _mod = importlib.import_module(f"xpoz.types.{_mod_info.name}")
        for _name in dir(_mod):
            _obj = getattr(_mod, _name)
            if isinstance(_obj, type) and issubclass(_obj, _PydBaseModel) and _obj is not _PydBaseModel:
                _patch_model_validate(_obj)
except Exception:
    pass  # SDK internals changed — fall through to default strict behavior.


PLATFORMS: dict = {
    "twitter": TwitterNamespace,
    "instagram": InstagramNamespace,
    "reddit": RedditNamespace,
    "tiktok": TiktokNamespace,
    "tracking": TrackingNamespace,
}


# ---------- typing helpers ----------

def _unwrap_optional(ann):
    origin = typing.get_origin(ann)
    if origin is typing.Union or origin is types.UnionType:
        args = [a for a in typing.get_args(ann) if a is not type(None)]
        if len(args) == 1:
            return args[0]
    return ann


def _is_list(ann):
    base = _unwrap_optional(ann)
    return typing.get_origin(base) in (list, typing.List)  # noqa: UP006


def _unwrap_inner_model(ann):
    """Strip Optional, then drill through generics (PaginatedResult[X], list[X])
    to the innermost class. Returns the class or None."""
    if ann is None or ann is inspect.Signature.empty:
        return None
    base = _unwrap_optional(ann)
    while True:
        origin = typing.get_origin(base)
        if origin is None:
            return base if inspect.isclass(base) else None
        args = typing.get_args(base)
        if not args:
            return origin if inspect.isclass(origin) else None
        base = _unwrap_optional(args[0])


def _resolve_fields_model(param_name: str, return_ann):
    """Fallback for SDKs without per-method `allowed_fields`: find the pydantic
    model whose `model_fields` are the valid values. Returns the class or None.

    The SDK >=0.6.2 attaches `method.allowed_fields = {param: frozenset[str]}`
    directly. Prefer that when present (see `_resolve_allowed_fields`)."""
    inner = _unwrap_inner_model(return_ann)
    if inner is None or not hasattr(inner, "model_fields"):
        return None
    if param_name == "fields":
        return inner
    if param_name.endswith("_fields"):
        stem = param_name[: -len("_fields")]
        for candidate in (stem, stem + "s"):
            if candidate in inner.model_fields:
                sub = _unwrap_inner_model(inner.model_fields[candidate].annotation)
                if sub is not None and hasattr(sub, "model_fields"):
                    return sub
    return None


def _resolve_allowed_fields(method, param_name: str, hints: dict) -> list[str] | None:
    """Return the sorted list of field names the API accepts for this method's
    `<param_name>` parameter. Prefers `method.allowed_fields[param_name]` from
    the SDK; falls back to `model.model_fields` for older SDKs."""
    af = getattr(method, "allowed_fields", None)
    if isinstance(af, dict) and param_name in af:
        return sorted(af[param_name])
    # Fallback for older SDK versions
    model = _resolve_fields_model(param_name, hints.get("return"))
    if model is not None:
        return sorted(model.model_fields)
    return None


def _first_doc_line(obj) -> str:
    doc = inspect.getdoc(obj) or ""
    return doc.strip().split("\n", 1)[0]


# ---------- auth config (plaintext JSON, gh/aws-cli style) ----------

def _config_path() -> str:
    if sys.platform == "win32":
        base = os.environ.get("APPDATA") or os.path.expanduser("~")
    else:
        base = os.environ.get("XDG_CONFIG_HOME") or os.path.join(os.path.expanduser("~"), ".config")
    return os.path.join(base, "xpoz", "config.json")


def _load_config() -> dict:
    try:
        with open(_config_path(), "r", encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def _save_config(cfg: dict) -> str:
    path = _config_path()
    parent = os.path.dirname(path)
    os.makedirs(parent, exist_ok=True)
    try:
        os.chmod(parent, 0o700)
    except (OSError, NotImplementedError):
        pass
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
    os.replace(tmp, path)
    try:
        os.chmod(path, 0o600)
    except (OSError, NotImplementedError):
        pass
    return path


def _delete_config() -> bool:
    try:
        os.remove(_config_path())
        return True
    except FileNotFoundError:
        return False


def _mask_key(key: str) -> str:
    if not key:
        return "(none)"
    return "…" + key[-4:] if len(key) > 4 else "…" + key


_SETTINGS_URL = "https://www.xpoz.ai/settings"


def _auth_login(args) -> int:
    api_key = args.api_key
    if not api_key:
        print(f"Get your API key from: {_SETTINGS_URL}")
        if sys.stdin.isatty():
            try:
                answer = input("Open in browser? [Y/n]: ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                sys.stderr.write("\nAborted.\n")
                return 1
            if answer in ("", "y", "yes"):
                try:
                    webbrowser.open(_SETTINGS_URL)
                except Exception:
                    pass
        try:
            api_key = input("Paste your API key: ").strip()
        except (EOFError, KeyboardInterrupt):
            sys.stderr.write("\nAborted.\n")
            return 1
    if not api_key:
        sys.stderr.write("No API key provided.\n")
        return 1
    cfg = _load_config()
    cfg["api_key"] = api_key
    if args.server_url:
        cfg["server_url"] = args.server_url
    path = _save_config(cfg)
    print(f"Stored credentials in {path}")
    return 0


def _auth_logout(_args) -> int:
    path = _config_path()
    if _delete_config():
        print(f"Removed {path}")
    else:
        print(f"No stored credentials at {path}")
    return 0


def _auth_status(_args) -> int:
    path = _config_path()
    cfg = _load_config()
    print(f"Config: {path}")
    if not cfg or not cfg.get("api_key"):
        print("Not logged in. Run `xpoz-cli auth login` to store an API key.")
        return 0
    print(f"API key: {_mask_key(cfg.get('api_key', ''))}")
    if cfg.get("server_url"):
        print(f"Server:  {cfg['server_url']}")
    return 0


_AUTH_DISPATCH = {
    "login": _auth_login,
    "logout": _auth_logout,
    "status": _auth_status,
}


# ---------- example synthesis ----------

_DOC_SECTION_RE = re.compile(
    r"^\s*(Args|Arguments|Parameters|Returns?|Raises|Yields|Examples?|Notes?|See Also)\s*:\s*$"
)


def _extract_doc_examples(obj) -> str:
    """Pull an 'Examples:' block out of a docstring, if present."""
    doc = inspect.getdoc(obj) or ""
    lines = doc.splitlines()
    start = None
    for i, line in enumerate(lines):
        m = _DOC_SECTION_RE.match(line)
        if m and m.group(1).lower().startswith("example"):
            start = i + 1
            break
    if start is None:
        return ""
    end = len(lines)
    for j in range(start, len(lines)):
        m = _DOC_SECTION_RE.match(lines[j])
        if m and not m.group(1).lower().startswith("example"):
            end = j
            break
    block = "\n".join(lines[start:end]).strip("\n")
    if not block.strip():
        return ""
    # Strip common leading whitespace so output isn't doubly indented.
    return inspect.cleandoc(block)


def _placeholder(name: str, ann) -> str:
    base = _unwrap_optional(ann)
    if inspect.isclass(base) and issubclass(base, Enum):
        first = next(iter(base), None)
        return first.name.lower() if first else "VALUE"
    if base is bool:
        return ""  # bool flag takes no value
    if _is_list(ann):
        return f"<{name}1> <{name}2>"
    if base is int:
        return "<N>"
    if base is float:
        return "<x>"
    return f"<{name}>"


def _synth_example(platform: str, method_name: str, sig: inspect.Signature, hints: dict) -> str:
    """Build a synthesized invocation line from a method's required params."""
    parts = [f"xpoz-cli {platform} {method_name}"]
    for pname, param in sig.parameters.items():
        if pname == "self":
            continue
        if param.default is not inspect.Parameter.empty:
            continue  # skip optional — keep the example minimal
        ann = hints.get(pname, str)
        flag = f"--{pname.replace('_', '-')}"
        ph = _placeholder(pname, ann)
        parts.append(f"{flag} {ph}".rstrip())
    return " ".join(parts)


def _build_method_epilog(platform: str, method_name: str, method, sig: inspect.Signature, hints: dict) -> str:
    synth = _synth_example(platform, method_name, sig, hints)
    doc_examples = _extract_doc_examples(method)
    blocks = [f"Examples:\n  {synth}"]
    if doc_examples:
        indented = "\n".join("  " + ln if ln else "" for ln in doc_examples.splitlines())
        blocks.append(f"From SDK docstring:\n{indented}")
    return "\n\n".join(blocks)


def _build_platform_epilog(platform: str, ns_cls) -> str:
    """Synthesize up to 2 example invocations drawn from the namespace's own methods."""
    examples: list[str] = []
    for mname in sorted(dir(ns_cls)):
        if mname.startswith("_") or len(examples) >= 2:
            continue
        method = getattr(ns_cls, mname)
        if not callable(method):
            continue
        try:
            sig = inspect.signature(method)
            hints = typing.get_type_hints(method)
        except Exception:
            continue
        examples.append("  " + _synth_example(platform, mname, sig, hints))
    if not examples:
        return ""
    return "Examples:\n" + "\n".join(examples) + "\n\nRun `xpoz-cli " + platform + " <method> --help` for per-method details."


# ---------- argparse construction ----------

def _add_param(parser: argparse.ArgumentParser, name: str, param, hints: dict, method=None) -> None:
    ann = hints.get(name, str)
    base = _unwrap_optional(ann)
    required = param.default is inspect.Parameter.empty
    flag = f"--{name.replace('_', '-')}"
    kwargs: dict = {"dest": name}

    if inspect.isclass(base) and issubclass(base, Enum):
        kwargs["choices"] = [e.name.lower() for e in base]
        kwargs["type"] = str
        if required:
            kwargs["required"] = True
    elif base is bool:
        kwargs["action"] = "store_true"
        kwargs["default"] = None  # None = "not set"
    elif _is_list(ann):
        kwargs["nargs"] = "+"
        if required:
            kwargs["required"] = True
    elif base is int:
        kwargs["type"] = int
        if required:
            kwargs["required"] = True
    elif base is float:
        kwargs["type"] = float
        if required:
            kwargs["required"] = True
    else:
        kwargs["type"] = str
        if required:
            kwargs["required"] = True

    help_parts: list[str] = []
    if name == "fields" or name.endswith("_fields"):
        allowed = _resolve_allowed_fields(method, name, hints) if method is not None else None
        if allowed is not None:
            help_parts.append("available: " + ", ".join(allowed))
            help_parts.append("[wildcards: 'all' (default — every available field), 'default' (SDK default)]")
    if not required and param.default not in (inspect.Parameter.empty, None):
        help_parts.append(f"(default: {param.default!r})")
    if help_parts:
        kwargs["help"] = " ".join(help_parts)

    try:
        parser.add_argument(flag, **kwargs)
    except argparse.ArgumentError:
        pass  # duplicate or unsupported — skip silently


def _add_method(sub, platform: str, name: str, method) -> None:
    try:
        sig = inspect.signature(method)
    except (TypeError, ValueError):
        return
    try:
        hints = typing.get_type_hints(method)
    except Exception:
        hints = {}

    p = sub.add_parser(
        name,
        help=_first_doc_line(method) or None,
        epilog=_build_method_epilog(platform, name, method, sig, hints),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    for pname, param in sig.parameters.items():
        if pname == "self":
            continue
        _add_param(p, pname, param, hints, method=method)
    p.set_defaults(_platform=platform, _method=name)


_TOP_LEVEL_EPILOG = """\
Examples:
  xpoz-cli twitter get_user --identifier elonmusk
  xpoz-cli twitter search_posts --query bitcoin --limit 20 --all-pages
  xpoz-cli reddit search_posts --query "python tutorial" --subreddit learnpython
  xpoz-cli twitter search_posts --query bitcoin --export-csv-url

Auth:
  --api-key KEY    (or env XPOZ_API_KEY)
  --server-url URL (or env XPOZ_SERVER_URL)

Discovery:
  xpoz-cli <platform> --help
  xpoz-cli <platform> <method> --help
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="xpoz-cli",
        description="Work seamlessly with Xpoz from the command line.",
        epilog=_TOP_LEVEL_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version", "-V",
        action="version",
        version=f"xpoz-cli {__version__}",
    )
    parser.add_argument("--api-key", help="Xpoz API key (or env XPOZ_API_KEY)")
    parser.add_argument("--server-url", help="Custom MCP server URL")
    parser.add_argument("--timeout", type=int, default=300, help="Operation timeout seconds (default 300)")
    parser.add_argument("--output", choices=["json", "pretty"], default="json")
    parser.add_argument("--all-pages", action="store_true",
                        help="Paginated results: walk every page and concatenate .data")
    parser.add_argument("--max-pages", type=int, default=None,
                        help="Cap for --all-pages (safety limit)")
    parser.add_argument("--page", type=int, default=None,
                        help="Paginated results: jump to this page number")
    parser.add_argument("--export-csv-url", action="store_true",
                        help="Call .export_csv() on the result and print the download URL")

    plat_sub = parser.add_subparsers(dest="platform", required=True, metavar="PLATFORM")
    for platform, ns_cls in PLATFORMS.items():
        pparser = plat_sub.add_parser(
            platform,
            help=f"{platform} methods",
            epilog=_build_platform_epilog(platform, ns_cls),
            formatter_class=argparse.RawDescriptionHelpFormatter,
        )
        msub = pparser.add_subparsers(dest="method", required=True, metavar="METHOD")
        for mname in sorted(dir(ns_cls)):
            if mname.startswith("_"):
                continue
            method = getattr(ns_cls, mname)
            if not callable(method):
                continue
            _add_method(msub, platform, mname, method)

    _add_auth_parser(plat_sub)
    return parser


def _add_auth_parser(plat_sub) -> None:
    auth_parser = plat_sub.add_parser(
        "auth",
        help="store, inspect, and remove persisted API credentials",
        description="Manage persisted Xpoz credentials (plaintext JSON, gh/aws-cli style).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  xpoz-cli auth login                       # prompt for API key\n"
            "  xpoz-cli auth login --api-key KEY         # non-interactive\n"
            "  xpoz-cli auth status\n"
            "  xpoz-cli auth logout\n"
        ),
    )
    auth_sub = auth_parser.add_subparsers(dest="auth_action", required=True, metavar="ACTION")

    login = auth_sub.add_parser("login", help="store an API key (prompts if not passed)")
    login.add_argument("--api-key", help="API key to store; if omitted, prompts via stdin (not echoed)")
    login.add_argument("--server-url", help="optional custom MCP server URL to persist alongside the key")

    auth_sub.add_parser("logout", help="remove stored credentials")
    auth_sub.add_parser("status", help="show whether credentials are stored and where")


# ---------- invocation ----------

def _collect_kwargs(args: argparse.Namespace, sig: inspect.Signature) -> dict:
    out: dict = {}
    for pname, param in sig.parameters.items():
        if pname == "self":
            continue
        if not hasattr(args, pname):
            continue
        val = getattr(args, pname)
        if val is None:
            continue
        if isinstance(val, bool) and val is False:
            continue
        out[pname] = val
    return out


def _flatten_error(exc: BaseException) -> str:
    parts: list[str] = []
    seen: set[int] = set()

    def visit(e: BaseException) -> None:
        if id(e) in seen:
            return
        seen.add(id(e))
        if isinstance(e, BaseExceptionGroup):
            for sub in e.exceptions:
                visit(sub)
            return
        parts.append(f"{type(e).__name__}: {e}")

    visit(exc)
    return " | ".join(parts) if parts else f"{type(exc).__name__}: {exc}"


def _coerce_enums(kwargs: dict) -> None:
    if "response_type" in kwargs and isinstance(kwargs["response_type"], str):
        key = kwargs["response_type"].upper()
        if key in ResponseType.__members__:
            kwargs["response_type"] = ResponseType[key]


_FIELDS_WILDCARDS = {"all", "default"}


def _expand_fields_kwargs(call_kwargs: dict, sig: inspect.Signature, method, hints: dict) -> None:
    """Resolve `--fields` / `--*-fields` wildcards and the implicit default.

    Behavior:
      no flag passed   → expand to method.allowed_fields[<param>]  (every API-queryable field)
      --fields all     → same as no flag
      --fields default → drop the kwarg so the SDK's own default applies
      --fields a b c   → pass through unchanged
    Mixing a wildcard with explicit names is rejected.

    Looks up the queryable set from `method.allowed_fields` (SDK >=0.6.2).
    Falls back to the result-model's `model_fields` for older SDKs.
    """
    for pname in sig.parameters:
        if pname == "self":
            continue
        if pname != "fields" and not pname.endswith("_fields"):
            continue

        val = call_kwargs.get(pname)

        # Determine intent
        if val is None:
            wildcard = "all"  # implicit default — give the user everything
        elif isinstance(val, list):
            wildcards = [v for v in val if v in _FIELDS_WILDCARDS]
            if wildcards:
                if len(val) > 1:
                    sys.stderr.write(
                        f"error: --{pname.replace('_', '-')}: "
                        f"'all' and 'default' cannot be combined with specific field names\n"
                    )
                    sys.exit(2)
                wildcard = wildcards[0]
            else:
                wildcard = None  # explicit list of field names
        else:
            wildcard = None

        if wildcard == "all":
            allowed = _resolve_allowed_fields(method, pname, hints)
            if allowed is not None:
                call_kwargs[pname] = list(allowed)
            else:
                call_kwargs.pop(pname, None)  # no metadata — fall back to SDK default
        elif wildcard == "default":
            call_kwargs.pop(pname, None)
        # else: explicit list of names — pass through unchanged


def _dump(obj):
    if obj is None or isinstance(obj, (str, int, float, bool)):
        return obj
    if hasattr(obj, "model_dump"):
        try:
            return obj.model_dump(mode="json")
        except Exception:
            return obj.model_dump()
    if isinstance(obj, dict):
        return {k: _dump(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_dump(x) for x in obj]
    if isinstance(obj, Enum):
        return obj.value
    return str(obj)


def _render_result(result, args) -> dict | list | str:
    # CSV export shortcut — either explicit --export-csv-url, or the user
    # asked for --response-type csv (which returns an empty .data with the
    # rows living server-side; .export_csv() yields the download URL).
    csv_mode = getattr(args, "response_type", None) == "csv"
    if (args.export_csv_url or csv_mode) and hasattr(result, "export_csv"):
        return {"csv_url": result.export_csv()}

    # Jump to a specific page
    if args.page is not None and hasattr(result, "get_page"):
        result = result.get_page(args.page)

    # Walk all pages
    if args.all_pages and hasattr(result, "data") and hasattr(result, "has_next_page"):
        items = list(result.data)
        fetched = 1
        cur = result
        while cur.has_next_page():
            if args.max_pages and fetched >= args.max_pages:
                break
            cur = cur.next_page()
            items.extend(cur.data)
            fetched += 1
        return {
            "data": [_dump(x) for x in items],
            "pages_fetched": fetched,
            "total_rows": getattr(getattr(result, "pagination", None), "total_rows", None),
        }

    # PaginatedResult → data + pagination metadata
    if hasattr(result, "data") and hasattr(result, "pagination"):
        return {
            "data": [_dump(x) for x in result.data],
            "pagination": _dump(result.pagination) if result.pagination else None,
        }

    return _dump(result)


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.platform == "auth":
        sys.exit(_AUTH_DISPATCH[args.auth_action](args))

    stored = _load_config()
    api_key = args.api_key or os.environ.get("XPOZ_API_KEY") or stored.get("api_key")
    if not api_key:
        sys.stderr.write(
            "Missing API key. Run `xpoz-cli auth login`, pass --api-key, or set XPOZ_API_KEY.\n"
        )
        sys.exit(2)

    client_kwargs: dict = {
        "timeout": args.timeout,
        "_user_agent": f"xpoz-cli/{__version__}",
    }
    server_url = args.server_url or os.environ.get("XPOZ_SERVER_URL") or stored.get("server_url")
    if server_url:
        client_kwargs["server_url"] = server_url

    try:
        client = XpozClient(api_key, **client_kwargs)
    except BaseException as e:
        sys.stderr.write(f"Failed to connect to Xpoz: {_flatten_error(e)}\n")
        sys.exit(1)

    try:
        ns = getattr(client, args.platform)
        method = getattr(ns, args.method)
        sig = inspect.signature(method)
        try:
            hints = typing.get_type_hints(method)
        except Exception:
            hints = {}
        call_kwargs = _collect_kwargs(args, sig)
        _coerce_enums(call_kwargs)
        _expand_fields_kwargs(call_kwargs, sig, method, hints)

        # Wall-clock timeout. The SDK's `timeout` argument only governs its
        # polling loop, not the underlying transport call — so a backend that
        # accepts the TCP connection but never sends a response can hang the
        # SDK indefinitely. We enforce `args.timeout` here at the CLI layer
        # by running the call in a daemon thread and giving up if it
        # doesn't finish in time. The thread is abandoned (process exits);
        # the OS reclaims its resources.
        import threading

        _result_holder: list = []
        _exc_holder: list = []

        def _runner():
            try:
                _result_holder.append(method(**call_kwargs))
            except BaseException as e:
                _exc_holder.append(e)

        worker = threading.Thread(target=_runner, daemon=True, name="xpoz-cli-call")
        worker.start()
        worker.join(timeout=args.timeout)
        if worker.is_alive():
            sys.stderr.write(
                f"timeout: operation did not complete within {args.timeout}s. "
                f"The backend may be unresponsive — try `--timeout N` for a longer "
                f"wait, or check the Xpoz status page.\n"
            )
            sys.stderr.flush()
            # When the SDK transport is stuck, normal Python cleanup (incl.
            # `client.close()` in the outer finally) also hangs because it
            # routes through the same blocked portal. `os._exit` bypasses
            # all cleanup; the OS reclaims fds and the daemon thread.
            os._exit(124)  # convention: 124 == timed out
        if _exc_holder:
            sys.stderr.write(f"{_flatten_error(_exc_holder[0])}\n")
            sys.exit(1)
        result = _result_holder[0]

        payload = _render_result(result, args)
    finally:
        try:
            client.close()
        except Exception:
            pass

    indent = 2 if args.output == "pretty" else None
    json.dump(payload, sys.stdout, indent=indent, ensure_ascii=False, default=str)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
